-- ════════════════════════════════════════════════════════════
--  FieldOps alter_v6.sql — Phase A: national org foundation
--  Run in Supabase → SQL Editor → New Query. Idempotent / safe to re-run.
--
--  Turns the flat "one manager sees everything" model into a regional
--  hierarchy for a national program:
--    • admin      (HQ) — sees & manages every region
--    • manager    (regional field manager) — only their own region
--    • ambassador — only their own events
--
--  Strategy:
--    1. regions table + region_id / manager_id on profiles.
--    2. region_id denormalized onto the high-volume tables so RLS is a
--       simple indexed comparison (no joins) at 300 demos/week.
--    3. Backfill legacy name-string links to ambassador_id (UUID-primary).
--    4. Region-scoped RLS on events / reports / payments / ambassadors.
--
--  ⚠️ After running, set yourself as HQ admin (see the BOOTSTRAP block at the
--     bottom) and create your regions, or managers will see nothing.
-- ════════════════════════════════════════════════════════════


-- ── 1. REGIONS ─────────────────────────────────────────────
create table if not exists regions (
  id          bigint generated by default as identity primary key,
  name        text not null,
  manager_id  uuid references profiles(id),   -- the regional lead
  created_at  timestamptz default now()
);
alter table regions enable row level security;

drop policy if exists "regions_admin"  on regions;
drop policy if exists "regions_select" on regions;
create policy "regions_admin"  on regions for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "regions_select" on regions for select to authenticated using (true);


-- ── 2. HIERARCHY COLUMNS ───────────────────────────────────
alter table profiles    add column if not exists region_id  bigint references regions(id);
alter table profiles    add column if not exists manager_id uuid   references profiles(id);

alter table events      add column if not exists region_id bigint references regions(id);
alter table reports     add column if not exists region_id bigint references regions(id);
alter table payments    add column if not exists region_id bigint references regions(id);
alter table ambassadors add column if not exists region_id bigint references regions(id);

create index if not exists idx_events_region   on events(region_id);
create index if not exists idx_reports_region  on reports(region_id);
create index if not exists idx_payments_region on payments(region_id);
create index if not exists idx_profiles_region on profiles(region_id);


-- ── 3. HELPERS ─────────────────────────────────────────────
create or replace function is_admin() returns boolean
  language sql security definer stable as $$
  select coalesce((select role from profiles where id = auth.uid()) = 'admin', false);
$$;

create or replace function get_my_region() returns bigint
  language sql security definer stable as $$
  select region_id from profiles where id = auth.uid();
$$;


-- ── 4. BACKFILL legacy name links → ambassador_id ──────────
update events    e  set ambassador_id = p.id from profiles p
  where e.ambassador_id  is null and e.ambassador  = p.name;
update reports   r  set ambassador_id = p.id from profiles p
  where r.ambassador_id  is null and r.ambassador  = p.name;
update payments  pm set ambassador_id = p.id from profiles p
  where pm.ambassador_id is null and pm.ambassador = p.name;


-- ── 5. REGION-SCOPED RLS ───────────────────────────────────
-- Pattern per table: admin = all · manager = own region · ambassador = own.
-- Ambassador policies that already exist are left in place.

-- EVENTS ----------------------------------------------------
drop policy if exists "events_manager" on events;
drop policy if exists "events_admin"   on events;
drop policy if exists "events_mgr"     on events;
create policy "events_admin" on events for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "events_mgr" on events for all to authenticated
  using    (get_my_role() = 'manager' and region_id = get_my_region())
  with check (get_my_role() = 'manager' and region_id = get_my_region());

-- REPORTS ---------------------------------------------------
drop policy if exists "rep_manager" on reports;
drop policy if exists "rep_admin"   on reports;
drop policy if exists "rep_mgr"     on reports;
create policy "rep_admin" on reports for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "rep_mgr" on reports for all to authenticated
  using    (get_my_role() = 'manager' and region_id = get_my_region())
  with check (get_my_role() = 'manager' and region_id = get_my_region());

-- PAYMENTS --------------------------------------------------
drop policy if exists "pay_manager" on payments;
drop policy if exists "pay_admin"   on payments;
drop policy if exists "pay_mgr"     on payments;
create policy "pay_admin" on payments for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "pay_mgr" on payments for all to authenticated
  using    (get_my_role() = 'manager' and region_id = get_my_region())
  with check (get_my_role() = 'manager' and region_id = get_my_region());

-- AMBASSADORS (roster) --------------------------------------
drop policy if exists "amb_manager"    on ambassadors;
drop policy if exists "amb_select_all" on ambassadors;
drop policy if exists "amb_admin"      on ambassadors;
drop policy if exists "amb_mgr"        on ambassadors;
drop policy if exists "amb_select"     on ambassadors;
create policy "amb_admin" on ambassadors for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "amb_mgr" on ambassadors for all to authenticated
  using    (get_my_role() = 'manager' and region_id = get_my_region())
  with check (get_my_role() = 'manager' and region_id = get_my_region());
create policy "amb_select" on ambassadors for select to authenticated
  using (is_admin() or region_id = get_my_region());

-- PROFILES: let admins assign people to regions ------------
drop policy if exists "profiles_update_admin" on profiles;
create policy "profiles_update_admin" on profiles for update to authenticated
  using (is_admin()) with check (is_admin());


-- ── 6. submit_report now stamps region_id ──────────────────
create or replace function submit_report(
  p_event_id bigint, p_units integer, p_samples integer, p_feedback text, p_photos integer
) returns void language plpgsql security definer set search_path = public as $$
declare
  v_uid uuid := auth.uid();
  v_name text; v_event events%rowtype; v_hours numeric := 0; v_rate numeric := 0;
begin
  select name into v_name from profiles where id = v_uid;
  select * into v_event from events
   where id = p_event_id and (ambassador_id = v_uid or ambassador = v_name);
  if not found then raise exception 'Event not found or not yours'; end if;

  if v_event.check_in_at is not null and v_event.check_out_at is not null then
    v_hours := round(extract(epoch from (v_event.check_out_at - v_event.check_in_at)) / 3600.0, 2);
  end if;
  select coalesce(rate, 0) into v_rate from ambassadors where name = v_name limit 1;
  v_rate := coalesce(v_rate, 0);

  insert into reports (event_name, ambassador, ambassador_id, region_id, date, status, units_sold, samples, feedback, photos, sales_lift)
  values (v_event.name, v_name, v_uid, v_event.region_id, coalesce(v_event.date, current_date), 'pending',
          coalesce(p_units, 0), coalesce(p_samples, 0), p_feedback, coalesce(p_photos, 0), 0);

  update events set status = 'completed', units_sold = p_units, samples = p_samples where id = p_event_id;

  if exists (select 1 from payments where event_name = v_event.name and ambassador = v_name) then
    update payments set hours = v_hours, rate = v_rate, total = round(v_hours * v_rate, 2)
     where event_name = v_event.name and ambassador = v_name;
  else
    insert into payments (ambassador, ambassador_id, region_id, event_name, date, hours, rate, expenses, total, status)
    values (v_name, v_uid, v_event.region_id, v_event.name, coalesce(v_event.date, current_date),
            v_hours, v_rate, 0, round(v_hours * v_rate, 2), 'pending');
  end if;
end;
$$;


-- ════════════════════════════════════════════════════════════
--  BOOTSTRAP — edit and run these two lines ONCE for yourself
-- ════════════════════════════════════════════════════════════
-- update profiles set role = 'admin' where email = 'YOUR_LOGIN_EMAIL';
-- insert into regions (name) values ('West'), ('Southwest'), ('Midwest');
